### ISSUE TITLE
Database tools are not available in Odoo 11

### ISSUE THREAD

**Issue by SalahAdDin** [ingadhoc/odoo-support#49] opened 2018-06-06 08:44 UTC
I installed that module but i can see it in app:
![deepinscreenshot_seleccionar area_20180606114127](https://user-images.githubusercontent.com/5034215/41027082-d916b22c-697e-11e8-885f-ee21fb404825.png)

I also installed `server_mode` and i can see it:
![deepinscreenshot_seleccionar area_20180606113602](https://user-images.githubusercontent.com/5034215/41027105-e1949e50-697e-11e8-9ff8-61ee944b0dc4.png)

What's the problem?

I reviewed all permissions:
```bash
 ls -l addons                                                                          ✔  3191  11:34:40 
total 104
drwxr-xr-x 7 salahaddin users 4096 abr  8 23:49 backend_theme_v11
drwxr-xr-x 9 salahaddin users 4096 abr 10 22:54 database_tools
drwxr-xr-x 5 salahaddin users 4096 jun  5 12:31 odoo-s3
drwxr-xr-x 9 salahaddin users 4096 jun  5 12:20 plm
drwxr-xr-x 6 salahaddin users 4096 jun  5 12:20 plm_auto_internalref
drwxr-xr-x 5 salahaddin users 4096 jun  5 12:20 plm_automated_convertion
drwxr-xr-x 6 salahaddin users 4096 jun  5 12:20 plm_automate_normal_bom
drwxr-xr-x 7 salahaddin users 4096 jun  5 12:20 plm_automatic_weight
drwxr-xr-x 5 salahaddin users 4096 jun  5 12:20 plm_box
drwxr-xr-x 6 salahaddin users 4096 jun  5 12:20 plm_client_customprocedure
drwxr-xr-x 5 salahaddin users 4096 jun  5 12:20 plm_compare_bom
drwxr-xr-x 8 salahaddin users 4096 jun  5 12:20 plm_cutted_parts
drwxr-xr-x 6 salahaddin users 4096 jun  5 12:20 plm_date_bom
drwxr-xr-x 5 salahaddin users 4096 jun  5 12:20 plm_engineering
drwxr-xr-x 7 salahaddin users 4096 jun  5 12:20 plm_pack_and_go
drwxr-xr-x 5 salahaddin users 4096 jun  5 12:20 plm_product_description_language_helper
drwxr-xr-x 6 salahaddin users 4096 jun  5 12:20 plm_project
drwxr-xr-x 5 salahaddin users 4096 jun  5 12:20 plm_report_language_helper
drwxr-xr-x 4 salahaddin users 4096 jun  5 12:20 plm_sale_fix
drwxr-xr-x 6 salahaddin users 4096 jun  5 12:20 plm_spare
drwxr-xr-x 5 salahaddin users 4096 jun  5 12:20 plm_suspended
drwxr-xr-x 6 salahaddin users 4096 jun  5 12:20 plm_web_revision
drwxr-xr-x 4 salahaddin users 4096 abr 10 22:54 server_mode
drwxr-xr-x 5 salahaddin users 4096 feb 26 13:44 theme_extensia
drwxr-xr-x 7 salahaddin users 4096 jun  5 10:36 web_environment_ribbon
drwxr-xr-x 6 salahaddin users 4096 jun  5 10:36 web_responsive
```
All is right.

**Comment by jjscarafia** [comment] 2018-06-06 20:53
Update module list, check addons path includes the module, etc. The issue is not regarding the module so I close it.

**Closed as completed by jjscarafia** 2018-06-06 20:53 UTC

**Comment by SalahAdDin** [comment] 2018-06-07 05:18
@jjscarafia I did it, many times, right now i can see the module but i cannot install it.

I installed fabric too:
```bash
odoo@d72ed48c889a:/$ pip3 install fabric
Collecting fabric
  Downloading https://files.pythonhosted.org/packages/ab/66/c4f9a1f6e50fbf783aab49eef620cb2ec5a8a1eb6cf834347beab4d381a3/fabric-2.1.3-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 394kB/s 
Collecting paramiko>=2.4 (from fabric)
  Downloading https://files.pythonhosted.org/packages/3e/db/cb7b6656e0e7387637ce850689084dc0b94b44df31cc52e5fc5c2c4fd2c1/paramiko-2.4.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 489kB/s 
Collecting cryptography>=1.1 (from fabric)
  Downloading https://files.pythonhosted.org/packages/fa/f4/3cde3604972dfa2b0fea85b9711948bb4fb70ab64095322aef35071bd254/cryptography-2.2.2-cp34-abi3-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 155kB/s 
Collecting invoke<2.0,>=1.0 (from fabric)
  Downloading https://files.pythonhosted.org/packages/6c/66/9e232c59e61f0a0b6552d68419a5c5a5dba368e105fdbfd2b6c74c402234/invoke-1.0.0-py3-none-any.whl (159kB)
    100% |████████████████████████████████| 163kB 336kB/s 
Collecting pyasn1>=0.1.7 (from paramiko>=2.4->fabric)
  Downloading https://files.pythonhosted.org/packages/a0/70/2c27740f08e477499ce19eefe05dbcae6f19fdc49e9e82ce4768be0643b9/pyasn1-0.4.3-py2.py3-none-any.whl (72kB)
    100% |████████████████████████████████| 81kB 473kB/s 
Collecting pynacl>=1.0.1 (from paramiko>=2.4->fabric)
  Downloading https://files.pythonhosted.org/packages/c9/9c/c8d4ae0f590faded4af55381131ad4db8729214eba6537c520622ba3548a/PyNaCl-1.2.1-cp35-cp35m-manylinux1_x86_64.whl (692kB)
    100% |████████████████████████████████| 696kB 143kB/s 
Collecting bcrypt>=3.1.3 (from paramiko>=2.4->fabric)
  Downloading https://files.pythonhosted.org/packages/72/8d/57da727cbb4ddf0295b0665a93bd8f46fbbd2a48b76cbb0896ca7d27301f/bcrypt-3.1.4-cp35-cp35m-manylinux1_x86_64.whl (54kB)
    100% |████████████████████████████████| 61kB 229kB/s 
Collecting idna>=2.1 (from cryptography>=1.1->fabric)
  Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 240kB/s 
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.1->fabric)
  Downloading https://files.pythonhosted.org/packages/59/cc/0e1635b4951021ef35f5c92b32c865ae605fac2a19d724fb6ff99d745c81/cffi-1.11.5-cp35-cp35m-manylinux1_x86_64.whl (420kB)
    100% |████████████████████████████████| 430kB 129kB/s 
Collecting asn1crypto>=0.21.0 (from cryptography>=1.1->fabric)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 150kB/s 
Collecting six>=1.4.1 (from cryptography>=1.1->fabric)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.1->fabric)
  Downloading https://files.pythonhosted.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 343kB/s 
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gvkc7sl9/pycparser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp8otuyj0vpip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pycparser
  Running setup.py clean for pycparser
Failed to build pycparser
Installing collected packages: idna, pycparser, cffi, asn1crypto, six, cryptography, pyasn1, pynacl, bcrypt, paramiko, invoke, fabric
  Running setup.py install for pycparser ... done
Successfully installed asn1crypto-0.24.0 bcrypt-3.1.4 cffi-1.11.5 cryptography-2.2.2 fabric-2.1.3 idna-2.6 invoke-1.0.0 paramiko-2.4.1 pyasn1-0.4.3 pycparser-2.18 pynacl-1.2.1 six-1.11.0
```

And still i cannot install it:
![deepinscreenshot_seleccionar area_20180607082346](https://user-images.githubusercontent.com/5034215/41079841-371aeb38-6a2c-11e8-8db0-b78946ed8aa5.png)

**Comment by jjscarafia** [comment] 2018-06-07 14:06
sorry, that module is not yet available for v11, you can check manifest key "installable"
https://github.com/ingadhoc/odoo-support/blob/11.0/database_tools/__manifest__.py#L45

when it becomes True is because it is migrated.

**Comment by SalahAdDin** [comment] 2018-06-07 14:10
@jjscarafia thank you.
